name: 'Test workflow'

# **What it does**: Renders the content of every page and check all internal links.
# **Why we have it**: To make sure all links connect correctly.
# **Who does it impact**: Docs content.

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: First-job-A
        run: |
          ls -al
      - name: First-job-B
        run: |
          echo "Hello"
  second_job:
    runs-on: ubuntu-latest
    needs: first_job
    steps:
      - name: Second-job-A
        run: |
          echo "Second"
      - name: Create annotation for build error
        run: |
          echo "::error file=app.js,line=1::Missing semicolon"
  third_job:
    runs-on: ubuntu-latest
    needs: second_job
    if: ${{ needs.second_job.result == 'success' }}
    steps:
      - name: I am the third
        run: |
          echo "I'm the third"
      - name: Previous job status
        run: |
          echo ${{ needs.second_job.result }}
  should_not_fail:
    runs-on: ubuntu-latest
    needs: second_job

    steps:
      - name: I am not failing
        run: |
          echo "I am doing well"

  fourth_job:
    runs-on: ubuntu-latest
    needs:
      - should_not_fail
    if: ${{ always() && needs.should_not_fail.result != 'failure' }}
    steps:
      - name: I am the fourth
        run: |
          echo "Running because previous not failing"
          echo ${{ needs.should_not_fail.result }}
  should_fail:
    runs-on: ubuntu-latest
    needs: second_job
    steps:
      - name: I am not skipping
        run: |
          echo "I am going rogue"
          exit 1
  fiftieth_job:
    runs-on: ubuntu-latest
    needs:
      - should_fail
    if: ${{ always() && needs.should_fail.result == 'skipped' }}
    steps:
      - name: I am the fiftieth
        run: |
          echo "NOT Running because previous was NOT skipped"